<?php declare(strict_types=1);
/** Safe, standalone supplier form view.
 *  - Works for both "create" (no $row) and "edit" (has $row with id)
 *  - No undefined $h / $row['id'] notices
 */

/** helpers & inputs */
$h    = fn($v)=>htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$base = $module_base ?? ($base ?? '');        // controller passes module_base
$row  = is_array($row ?? null) ? $row : [];   // always an array
$ok   = $_SESSION['flash_ok']  ?? null; unset($_SESSION['flash_ok']);
$err  = $_SESSION['flash_err'] ?? null; unset($_SESSION['flash_err']);

/** normalized fields */
$id              = isset($row['id']) ? (int)$row['id'] : 0;
$isEdit          = $id > 0;
$code            = (string)($row['code']            ?? '');
$name            = (string)($row['name']            ?? '');
$phone           = (string)($row['phone']           ?? '');
$email           = (string)($row['email']           ?? '');
$address         = (string)($row['address']         ?? '');
$tax_reg_no      = (string)($row['tax_reg_no']      ?? '');
$opening_balance = (string)($row['opening_balance'] ?? '0.00');
$status          = (string)($row['status']          ?? 'active');

$action = $isEdit ? ($base . '/suppliers/' . $id) : ($base . '/suppliers');
$viewUrl = $isEdit ? ($base . '/suppliers/' . $id) : null;
$purchasesUrl = $isEdit ? ($base . '/purchases?supplier_id=' . $id) : null;
$productsUrl  = $isEdit ? ($base . '/products?supplier_id=' . $id)  : null;
$deleteUrl    = $isEdit ? ($base . '/suppliers/' . $id . '/delete') : null;
?>
<div class="max-w-4xl">
  <!-- Header -->
  <div class="flex items-center justify-between mb-5">
    <h1 class="text-2xl font-semibold text-slate-900 dark:text-slate-100">
      <?= $isEdit ? 'Edit Supplier' : 'New Supplier' ?>
    </h1>
    <div class="flex items-center gap-2">
      <?php if ($isEdit && $viewUrl): ?>
        <a href="<?= $h($viewUrl) ?>"
           class="inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-slate-200 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">
          <i class="fa-regular fa-eye"></i><span>View</span>
        </a>
      <?php endif; ?>
      <a href="<?= $h($base.'/suppliers') ?>"
         class="inline-flex items-center gap-2 px-3 py-2 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700">
        <i class="fa-solid fa-arrow-left"></i><span>Back</span>
      </a>
    </div>
  </div>

  <!-- Flashes -->
  <?php if ($ok): ?>
    <div class="mb-4 rounded-lg bg-emerald-50 text-emerald-800 px-4 py-3 text-sm flex items-center gap-2">
      <i class="fa-solid fa-circle-check"></i><?= $h($ok) ?>
    </div>
  <?php endif; ?>
  <?php if ($err): ?>
    <div class="mb-4 rounded-lg bg-rose-50 text-rose-800 px-4 py-3 text-sm flex items-center gap-2">
      <i class="fa-solid fa-triangle-exclamation"></i><?= $h($err) ?>
    </div>
  <?php endif; ?>

  <!-- Form -->
  <form method="post" action="<?= $h($action) ?>" class="grid grid-cols-1 md:grid-cols-2 gap-5">
    <!-- Supplier Code (LOCKED / NON-EDITABLE) -->
    <div class="md:col-span-1">
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Supplier Code</label>
      <?php if ($code !== ''): ?>
        <input type="text" value="<?= $h($code) ?>" readonly disabled
               class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 bg-slate-100 text-slate-600 dark:bg-slate-900/50 cursor-not-allowed"/>
        <p class="text-xs text-slate-500 mt-1">Auto-generated by the system. This cannot be changed.</p>
      <?php else: ?>
        <input type="text" value="(will be assigned on save)" readonly disabled
               class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 bg-slate-100 text-slate-500 italic dark:bg-slate-900/50 cursor-not-allowed"/>
        <p class="text-xs text-slate-500 mt-1">The next code (e.g. SUP-<?= date('Y') ?>-0001) will be assigned when you save.</p>
      <?php endif; ?>
    </div>

    <!-- Name -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Name *</label>
      <input name="name" required value="<?= $h($name) ?>"
             class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"/>
    </div>

    <!-- Phone -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Phone</label>
      <input name="phone" value="<?= $h($phone) ?>"
             class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"/>
    </div>

    <!-- Email -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Email</label>
      <input name="email" type="email" value="<?= $h($email) ?>"
             class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"/>
    </div>

    <!-- Tax Reg. No. -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Tax Reg. No.</label>
      <input name="tax_reg_no" value="<?= $h($tax_reg_no) ?>"
             class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"/>
    </div>

    <!-- Opening balance -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Opening Balance</label>
      <input name="opening_balance" type="number" step="0.01"
             value="<?= $h($opening_balance) ?>"
             class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"/>
    </div>

    <!-- Address -->
    <div class="md:col-span-2">
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Address</label>
      <textarea name="address" rows="3"
                class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900"><?= $h($address) ?></textarea>
    </div>

    <!-- Status -->
    <div>
      <label class="block text-sm text-slate-600 dark:text-slate-300 mb-1">Status</label>
      <select name="status"
              class="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2 dark:bg-slate-900">
        <option value="active"   <?= $status==='inactive' ? '' : 'selected' ?>>active</option>
        <option value="inactive" <?= $status==='inactive' ? 'selected' : '' ?>>inactive</option>
      </select>
    </div>

    <!-- Actions -->
    <div class="md:col-span-2 flex flex-wrap items-center gap-3 pt-2">
      <button class="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700">
        <i class="fa-solid fa-floppy-disk"></i><span>Save</span>
      </button>

      <?php if ($isEdit && $deleteUrl): ?>
        <form method="post" action="<?= $h($deleteUrl) ?>"
              onsubmit="return confirm('Disable this supplier?')">
          <button type="submit"
            class="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-rose-50 text-rose-700 hover:bg-rose-100 dark:bg-rose-900/20 dark:text-rose-300 dark:hover:bg-rose-900/30">
            <i class="fa-solid fa-ban"></i><span>Disable</span>
          </button>
        </form>
      <?php endif; ?>

      <?php if ($isEdit && $purchasesUrl): ?>
        <a href="<?= $h($purchasesUrl) ?>"
           class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-200 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">
          <i class="fa-solid fa-cart-shopping"></i><span>View Purchases</span>
        </a>
      <?php endif; ?>

      <?php if ($isEdit && $productsUrl): ?>
        <a href="<?= $h($productsUrl) ?>"
           class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-200 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">
          <i class="fa-solid fa-boxes-stacked"></i><span>Products from Supplier</span>
        </a>
      <?php endif; ?>
    </div>
  </form>
</div>